name: Docs CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (markdownlint-cli2)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install markdownlint
        run: npm i -g markdownlint-cli2

      - name: Markdown Lint
        run: markdownlint-cli2 "**/*.md" "#node_modules" "#.git" --config .markdownlint.jsonc

      - name: Link Checker (lychee)
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose
            --no-progress
            --timeout 20
            --max-redirects 5
            --retry-wait-time 2
            --exclude-all-private
            --cache
            --accept 200,206,429
            --exclude-file .lycheeignore
            .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Codespell
        uses: codespell-project/actions-codespell@v2
        with:
          ignore_words_list: iobeats,IOB,DeFi,Multichain,OpenZeppelin
          skip: .git,*.pdf,*.png,*.jpg,*.gif,node_modules
          check_filenames: true
